name: dsi_participant
channels:
  - conda-forge
  - defaults
dependencies:
  - absl-py=2.1.0=pyhd8ed1ab_0
  - aiohttp=3.9.3=py311h05b510d_1
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - aom=3.7.1=h463b476_0
  - appnope=0.1.4=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - attrs=23.2.0=pyh71513ae_0
  - aws-c-auth=0.7.11=ha4ce7b8_1
  - aws-c-cal=0.6.9=h4fd42c2_3
  - aws-c-common=0.9.12=h93a5062_0
  - aws-c-compression=0.2.17=h4fd42c2_8
  - aws-c-event-stream=0.4.1=he66824e_2
  - aws-c-http=0.8.0=hd3d28cd_2
  - aws-c-io=0.14.0=h8daa835_1
  - aws-c-mqtt=0.10.1=h59ff425_0
  - aws-c-s3=0.4.9=h7f99a2c_0
  - aws-c-sdkutils=0.1.13=h4fd42c2_1
  - aws-checksums=0.1.17=h4fd42c2_7
  - aws-crt-cpp=0.26.0=hfff802b_8
  - aws-sdk-cpp=1.11.210=he93ac2d_10
  - blinker=1.7.0=pyhd8ed1ab_0
  - blosc=1.21.5=hc338f07_0
  - bokeh=3.4.0=pyhd8ed1ab_0
  - brotli=1.1.0=hb547adb_1
  - brotli-bin=1.1.0=hb547adb_1
  - brotli-python=1.1.0=py311ha891d26_1
  - brunsli=0.1=h9f76cd9_0
  - bzip2=1.0.8=h93a5062_5
  - c-ares=1.27.0=h93a5062_0
  - c-blosc2=2.14.3=ha57e6be_0
  - ca-certificates=2024.2.2=hf0a4a13_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.3.3=pyhd8ed1ab_0
  - cairo=1.18.0=hd1e100b_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - cffi=1.16.0=py311h4a08483_0
  - charls=2.4.2=h13dd4ca_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - clarabel=0.7.1=py311h3a77de1_0
  - click=8.1.7=unix_pyh707e725_0
  - cloudpickle=3.0.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.2.0=py311hd03642b_0
  - cryptography=42.0.5=py311h71175c2_0
  - cvxopt=1.3.2=py311hd76776f_1
  - cvxpy=1.4.2=py311ha1ab1f8_1
  - cvxpy-base=1.4.2=py311hfbe21a1_1
  - cycler=0.12.1=pyhd8ed1ab_0
  - cytoolz=0.12.3=py311h05b510d_0
  - dask=2024.2.0=pyhd8ed1ab_0
  - dask-core=2024.2.0=pyhd8ed1ab_0
  - dask-expr=0.4.1=pyhd8ed1ab_0
  - datasets=2.14.4=pyhd8ed1ab_0
  - dav1d=1.2.1=hb547adb_0
  - debugpy=1.8.1=py311h92babd0_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - dill=0.3.7=pyhd8ed1ab_0
  - distributed=2024.2.0=pyhd8ed1ab_0
  - docopt=0.6.2=py_1
  - dsdp=5.8=h9397a75_1203
  - ecos=2.0.13=py311h9ea6feb_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.6.2=hebf3989_0
  - fancyimpute=0.7.0=pyhd8ed1ab_0
  - ffmpeg=6.1.1=gpl_ha63e52a_101
  - fftw=3.3.10=nompi_h3046061_108
  - filelock=3.13.3=pyhd8ed1ab_0
  - flatbuffers=23.5.26=h13dd4ca_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_1
  - fontconfig=2.14.2=h82840c6_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.50.0=py311h05b510d_0
  - freetype=2.12.1=hadb7bae_2
  - fribidi=1.0.10=h27ca646_0
  - frozenlist=1.4.1=py311h05b510d_0
  - fsspec=2024.3.1=pyhca7485f_0
  - gast=0.5.4=pyhd8ed1ab_0
  - gettext=0.22.5=h8fbad5d_2
  - gettext-tools=0.22.5=h8fbad5d_2
  - gflags=2.2.2=hc88da5d_1004
  - giflib=5.2.1=h1a8c8d9_3
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.42=pyhd8ed1ab_0
  - glog=0.6.0=h6da1cb0_0
  - glpk=5.0=h6d7a090_0
  - gmp=6.3.0=hebf3989_1
  - gnutls=3.7.9=hd26332c_0
  - google-auth=2.29.0=pyhca7485f_0
  - google-auth-oauthlib=1.2.0=pyhd8ed1ab_0
  - google-pasta=0.2.0=pyh8c360ce_0
  - graphite2=1.3.13=hebf3989_1003
  - greenlet=3.0.3=py311h92babd0_0
  - grpcio=1.59.3=py311hf5d242d_0
  - gsl=2.7=h6e638da_0
  - h5py=3.10.0=nompi_py311hd00467f_101
  - harfbuzz=8.3.0=h8f0ba13_0
  - hdf5=1.14.3=nompi_h5bb55e9_100
  - huggingface_hub=0.22.2=pyhd8ed1ab_0
  - icu=73.2=hc8870d7_0
  - idna=3.6=pyhd8ed1ab_0
  - imagecodecs=2024.1.1=py311h9a59f95_3
  - imageio=2.34.0=pyh4b66e23_0
  - importlib-metadata=7.1.0=pyha770c72_0
  - importlib_metadata=7.1.0=hd8ed1ab_0
  - importlib_resources=6.4.0=pyhd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - ipykernel=6.29.3=pyh3cd1d5f_0
  - ipython=8.22.2=pyh707e725_0
  - jasper=4.2.3=h7c0e182_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.3=pyhd8ed1ab_0
  - joblib=1.3.2=pyhd8ed1ab_0
  - jsonpickle=3.0.2=pyhd8ed1ab_1
  - jsonschema=4.21.1=pyhd8ed1ab_0
  - jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
  - jupyter_client=8.6.1=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py311h267d04e_0
  - jxrlib=1.1=h93a5062_3
  - keras=2.15.0=pyhd8ed1ab_0
  - kiwisolver=1.4.5=py311he4fd1f5_1
  - knnimpute=0.1.0=pyhd8ed1ab_0
  - krb5=1.21.2=h92f50d5_0
  - lame=3.100=h1a8c8d9_1003
  - lazy_loader=0.4=pyhd8ed1ab_0
  - lcms2=2.16=ha0e7c42_0
  - lerc=4.0.0=h9a09cb3_0
  - libabseil=20230802.1=cxx17_h13dd4ca_0
  - libaec=1.1.3=hebf3989_0
  - libarrow=15.0.0=h4ce3932_0_cpu
  - libarrow-acero=15.0.0=h13dd4ca_0_cpu
  - libarrow-dataset=15.0.0=h13dd4ca_0_cpu
  - libarrow-flight=15.0.0=ha94d253_0_cpu
  - libarrow-flight-sql=15.0.0=h39a9b85_0_cpu
  - libarrow-gandiva=15.0.0=hf757142_0_cpu
  - libarrow-substrait=15.0.0=h7fd9903_0_cpu
  - libasprintf=0.22.5=h8fbad5d_2
  - libasprintf-devel=0.22.5=h8fbad5d_2
  - libass=0.17.1=hf7da4fe_1
  - libavif16=1.0.3=he23855c_1
  - libblas=3.9.0=21_osxarm64_openblas
  - libbrotlicommon=1.1.0=hb547adb_1
  - libbrotlidec=1.1.0=hb547adb_1
  - libbrotlienc=1.1.0=hb547adb_1
  - libcblas=3.9.0=21_osxarm64_openblas
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.7.1=h2d989ff_0
  - libcxx=16.0.6=h4653b0c_0
  - libdeflate=1.20=h93a5062_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h93a5062_2
  - libevent=2.1.12=h2757513_1
  - libexpat=2.6.2=hebf3989_0
  - libffi=3.4.2=h3422bc3_5
  - libgettextpo=0.22.5=h8fbad5d_2
  - libgettextpo-devel=0.22.5=h8fbad5d_2
  - libgfortran=5.0.0=13_2_0_hd922786_3
  - libgfortran5=13.2.0=hf226fd6_3
  - libglib=2.80.0=hfc324ee_3
  - libgoogle-cloud=2.12.0=hfb399a7_4
  - libgrpc=1.59.3=h9560976_0
  - libhwloc=2.9.3=default_h4394839_1009
  - libhwy=1.1.0=h2ffa867_0
  - libiconv=1.17=h0d3ecfb_2
  - libidn2=2.3.7=h93a5062_0
  - libintl=0.22.5=h8fbad5d_2
  - libintl-devel=0.22.5=h8fbad5d_2
  - libjpeg-turbo=3.0.0=hb547adb_1
  - libjxl=0.10.1=h07599a0_1
  - liblapack=3.9.0=21_osxarm64_openblas
  - liblapacke=3.9.0=21_osxarm64_openblas
  - libllvm14=14.0.6=hd1a9a77_4
  - libllvm15=15.0.7=h2621b3d_4
  - libllvm16=16.0.6=haab561b_3
  - libnghttp2=1.58.0=ha4dd798_1
  - libopenblas=0.3.26=openmp_h6c19121_0
  - libopencv=4.9.0=py311h22734c1_5
  - libopenvino=2023.2.0=he6dadac_4
  - libopenvino-arm-cpu-plugin=2023.2.0=he6dadac_4
  - libopenvino-auto-batch-plugin=2023.2.0=hc9f00d9_4
  - libopenvino-auto-plugin=2023.2.0=hc9f00d9_4
  - libopenvino-hetero-plugin=2023.2.0=hf483cef_4
  - libopenvino-ir-frontend=2023.2.0=hf483cef_4
  - libopenvino-onnx-frontend=2023.2.0=h7939876_4
  - libopenvino-paddle-frontend=2023.2.0=h7939876_4
  - libopenvino-pytorch-frontend=2023.2.0=hebf3989_4
  - libopenvino-tensorflow-frontend=2023.2.0=he0d35a2_4
  - libopenvino-tensorflow-lite-frontend=2023.2.0=hebf3989_4
  - libopus=1.3.1=h27ca646_1
  - libosqp=0.6.3=h313beb8_0
  - libparquet=15.0.0=hf6ce1d5_0_cpu
  - libpng=1.6.43=h091b4b1_0
  - libpq=16.2=h0f8b458_1
  - libprotobuf=4.24.4=h810fc01_0
  - libqdldl=0.1.7=hb7217d7_0
  - libre2-11=2023.09.01=h741fcf5_1
  - libsodium=1.0.18=h27ca646_1
  - libsqlite=3.45.2=h091b4b1_0
  - libssh2=1.11.0=h7a5bd25_0
  - libtasn1=4.19.0=h1a8c8d9_0
  - libthrift=0.19.0=h026a170_1
  - libtiff=4.6.0=h07db509_3
  - libunistring=0.9.10=h3422bc3_0
  - libutf8proc=2.8.0=h1a8c8d9_0
  - libvpx=1.13.1=hb765f3a_0
  - libwebp-base=1.3.2=hb547adb_0
  - libxcb=1.15=hf346824_0
  - libxml2=2.12.6=h0d0cfa8_1
  - libzlib=1.2.13=h53f4e23_5
  - libzopfli=1.0.3=h9f76cd9_0
  - llvm-openmp=18.1.2=hcd81f8e_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.3.3=py311hd44b8e9_0
  - lz4-c=1.9.4=hb7217d7_0
  - markdown=3.6=pyhd8ed1ab_0
  - markupsafe=2.1.5=py311h05b510d_0
  - matplotlib-base=3.8.3=py311hb58f1d1_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - metis=5.1.0=h13dd4ca_1007
  - missingno=0.5.2=pyhd8ed1ab_0
  - ml_dtypes=0.2.0=py311h9e438b8_2
  - mpfr=4.2.1=h9546428_0
  - msgpack-python=1.0.7=py311hd03642b_0
  - multidict=6.0.5=py311he2be06e_0
  - multiprocess=0.70.15=py311heffc1b2_1
  - munch=4.0.0=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbformat=5.10.4=pyhd8ed1ab_0
  - ncurses=6.4.20240210=h078ce10_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - nettle=3.9.1=h40ed0f5_0
  - nose=1.3.7=py_1006
  - numba=0.59.1=py311h00351ea_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - opencv=4.9.0=py311h24019a2_5
  - openh264=2.4.0=h965bd2d_0
  - openjpeg=2.5.2=h9f1df11_0
  - openssl=3.2.1=h0d3ecfb_1
  - opt_einsum=3.3.0=pyhc1e730c_2
  - orc=1.9.2=h7c018df_0
  - osqp=0.6.3=py311h6e08293_2
  - p11-kit=0.24.1=h29577a5_0
  - packaging=24.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - partd=1.4.1=pyhd8ed1ab_0
  - patsy=0.5.6=pyhd8ed1ab_0
  - pcre2=10.43=h26f9a81_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.2.0=py311hb9c5795_0
  - pip=24.0=pyhd8ed1ab_0
  - pixman=0.43.4=hebf3989_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.2.0=pyhd8ed1ab_0
  - plotly=5.19.0=pyhd8ed1ab_0
  - pluggy=1.4.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - protobuf=4.24.4=py311h4d1eceb_0
  - psutil=5.9.8=py311h05b510d_0
  - psycopg2=2.9.9=py311h589e011_0
  - pthread-stubs=0.4=h27ca646_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pugixml=1.14=h13dd4ca_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py-cpuinfo=9.0.0=pyhd8ed1ab_0
  - py-opencv=4.9.0=py311hee96954_5
  - pyarrow=15.0.0=py311hd7bc329_0_cpu
  - pyarrow-hotfix=0.6=pyhd8ed1ab_0
  - pyasn1=0.5.1=pyhd8ed1ab_0
  - pyasn1-modules=0.3.0=pyhd8ed1ab_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pyjwt=2.8.0=pyhd8ed1ab_1
  - pyopenssl=24.0.0=pyhd8ed1ab_0
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - pytest=8.1.1=pyhd8ed1ab_0
  - python=3.11.8=hdf0ec26_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-dotenv=1.0.1=pyhd8ed1ab_0
  - python-fastjsonschema=2.19.1=pyhd8ed1ab_0
  - python-flatbuffers=24.3.25=pyh59ac667_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python-xxhash=3.4.1=py311heffc1b2_0
  - python_abi=3.11=4_cp311
  - pytz=2024.1=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pywavelets=1.4.1=py311hb49d859_1
  - pyyaml=6.0.1=py311heffc1b2_1
  - pyzmq=25.1.2=py311h6727e71_0
  - qdldl-python=0.1.7.post0=py311hfbe21a1_1
  - rav1e=0.6.6=h69fbcac_2
  - re2=2023.09.01=h4cba328_1
  - readline=8.2=h92ec313_1
  - referencing=0.34.0=pyhd8ed1ab_0
  - regex=2023.12.25=py311h05b510d_0
  - requests=2.31.0=pyhd8ed1ab_0
  - requests-oauthlib=2.0.0=pyhd8ed1ab_0
  - rpds-py=0.18.0=py311ha958965_0
  - rsa=4.9=pyhd8ed1ab_0
  - sacred=0.8.5=pyhd8ed1ab_0
  - safetensors=0.4.2=py311h94f323b_0
  - scikit-image=0.22.0=py311h6e08293_2
  - scikit-learn=1.4.1.post1=py311h696fe38_0
  - scipy=1.12.0=py311h4f9446f_2
  - scs=3.2.4.post1=py311h8ee0600_1
  - seaborn=0.13.2=hd8ed1ab_0
  - seaborn-base=0.13.2=pyhd8ed1ab_0
  - setuptools=69.2.0=pyhd8ed1ab_0
  - shap=0.44.1=cpu_py311ha234ae0_0
  - six=1.16.0=pyh6c4a22f_0
  - slicer=0.0.7=pyhd8ed1ab_0
  - smmap=5.0.0=pyhd8ed1ab_0
  - snappy=1.1.10=h17c5cce_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - sqlalchemy=2.0.27=py311h05b510d_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.1=py311h9ea6feb_0
  - suitesparse=5.10.1=h79486c6_3
  - svt-av1=1.8.0=h463b476_0
  - tbb=2021.11.0=h2ffa867_1
  - tblib=3.0.0=pyhd8ed1ab_0
  - tenacity=8.2.3=pyhd8ed1ab_0
  - tensorboard=2.15.2=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py311h5fb2c35_1
  - tensorflow=2.15.0=cpu_py311h9b82b1a_2
  - tensorflow-base=2.15.0=cpu_py311he034567_2
  - tensorflow-estimator=2.15.0=cpu_py311hcceb7c1_2
  - termcolor=2.4.0=pyhd8ed1ab_0
  - threadpoolctl=3.4.0=pyhc1e730c_0
  - tifffile=2024.2.12=pyhd8ed1ab_0
  - tk=8.6.13=h5083fa2_1
  - tokenizers=0.15.2=py311hcd5b669_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - toolz=0.12.1=pyhd8ed1ab_0
  - tornado=6.4=py311h05b510d_0
  - tqdm=4.66.2=pyhd8ed1ab_0
  - traitlets=5.14.2=pyhd8ed1ab_0
  - transformers=4.39.3=pyhd8ed1ab_0
  - typing-extensions=4.10.0=hd8ed1ab_0
  - typing_extensions=4.10.0=pyha770c72_0
  - tzdata=2024a=h0c530f3_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - werkzeug=3.0.2=pyhd8ed1ab_0
  - wheel=0.43.0=pyhd8ed1ab_0
  - wrapt=1.14.1=py311he2be06e_1
  - x264=1!164.3095=h57fd34a_2
  - x265=3.5=hbc6ce65_3
  - xorg-libxau=1.0.11=hb547adb_0
  - xorg-libxdmcp=1.1.3=h27ca646_0
  - xxhash=0.8.2=hb547adb_0
  - xyzservices=2023.10.1=pyhd8ed1ab_0
  - xz=5.2.6=h57fd34a_0
  - yaml=0.2.5=h3422bc3_2
  - yarl=1.9.4=py311h05b510d_0
  - zeromq=4.3.5=hebf3989_1
  - zfp=1.0.1=ha8f4885_0
  - zict=3.0.0=pyhd8ed1ab_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=h53f4e23_5
  - zlib-ng=2.0.7=h1a8c8d9_0
  - zstd=1.5.5=h4f39d0f_0
  - pip:
      - appdirs==1.4.4
      - autograd==1.6.2
      - autograd-gamma==0.5.0
      - beautifulsoup4==4.12.3
      - faraway==0.0.6
      - formulaic==1.0.1
      - frozendict==2.4.0
      - future==1.0.0
      - html5lib==1.1
      - interface-meta==1.3.0
      - islp==0.3.22
      - l0bnb==1.0.0
      - lifelines==0.28.0
      - lightning-utilities==0.11.1
      - llvmlite==0.42.0
      - lxml==5.1.0
      - mpmath==1.3.0
      - multitasking==0.0.11
      - networkx==3.2.1
      - numpy==1.24.4
      - pandas==1.5.3
      - peewee==3.17.1
      - progressbar2==4.4.2
      - pygam==0.9.0
      - python-utils==3.8.2
      - pytorch-lightning==2.2.1
      - soupsieve==2.5
      - sympy==1.12
      - torch==2.2.1
      - torchmetrics==1.3.2
      - webencodings==0.5.1
      - yfinance==0.2.37